# =========================== DESCRIPTION DU SITE =============================
site_name: MyDocs
site_author: Alex Lamizana
site_url: https://lamizana.github.io/MyDocs/
site_description: Documentation sur la programmation

# =============================== NAVIGATION ==================================
nav:
  - Home: index.md

  - Projets:
      - projets/index.md
      - So Long: projets/so_long.md
      - Push Swap: projets/push_swap.md

  - Javascript:
      - Bases: javascript/bases.md
      - Redux: javascript/redux.md
      - React: javascript/react.md

  - GitHub:
      - github/github.md

  - Mkdocs:
      - mkdocs/index.md
      - Bases: mkdocs/bases.md
      - Material: mkdocs/material.md

  - About: about.md

# =============================== THEME DU SITE ================================
theme:
  name: material # mkdocs,readthedocs, material
  language: fr
  palette:
    # Toogle Mode clair :
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Passer en mode sombre

    # Toogle Mode sombre :
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Passer en mode clair

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.path
    - navigation.top
    - navigation.sections
    - navigation.prune
    - navigation.indexes

    # - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - header.autohide

  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/bat
  favicon: favicon.png

  # Dossier pour les fichiers personnalisés
  custom_dir: overrides

# ============================ EXTENSIONS MARKDOWN =============================
markdown_extensions:
  # Python Markdown
  - attr_list
  - md_in_html

  # Python Markdown Extensions
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator:
        !!python/name:material.extensions.emoji.to_svg # ==================================== CSS ====================================


extra_css:
  - css/custom.css

# ======================== Configuration des versions =========================
extra:
  version: 1.0.0
  copyright: MyDocs Copyright (c) 2026 Alex Lamizana

  # Consentement pour resencement :
  consent:
    title: Consentement aux cookies
    description: >-
      Nous utilisons des cookies pour reconnaître vos visites répétées et vos préférences, ainsi que pour mesurer l'efficacité de notre documentation et déterminer si les utilisateurs trouvent ce qu'ils recherchent. En donnant votre consentement, vous nous aidez à améliorer notre documentation.
    cookies:
      analytics:
        name: Google Analytics
        provider: google
        checked: false
        property: G-74MZWWS1RR
